// Guards against reintroducing the copy that got v1.0(3) rejected.
//
// Apple Guideline 3.1.1 forbids steering users to an external purchase or
// setup flow. GrowSense was rejected partly for exactly this, and the fix
// (commit 76cc70f) reworded several strings — but only in en and th, and
// only in assets/locales/, which are GENERATED by tool/sync_locales.js.
// The source (tool/flutter_extra_keys.json) still carried the old wording,
// so a routine regeneration would have silently restored it.
//
// This test reads the shipped locale assets in every language, so it fails
// whether the regression arrives from a translator, a hand-edit, or a
// regeneration from stale source.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

const _langs = ['en', 'th', 'vi', 'ko', 'zh', 'ar'];

/// Substrings that mean "go to the web app" in each shipped language.
const _steering = <String>[
  'web app',
  'webapp',
  'เว็บแอป', // th
  'ứng dụng web', // vi
  '웹 앱', // ko
  '网页应用', // zh
  '網頁應用', // zh-Hant, in case a locale is added
  'تطبيق الويب', // ar
];

/// Known, deliberate exception.
///
/// flutter.sub.manage_web renders only inside _SubscriptionCard, which is
/// hidden on iOS today. When that card is un-gated for In-App Purchase it
/// must be placed behind kShowWebBillingCopy — at which point this
/// exemption should be reconsidered rather than quietly widened.
const _allowedKeys = <String>{'flutter.sub.manage_web'};

void main() {
  test('no locale steers users to the web app', () {
    final offenders = <String>[];

    for (final lang in _langs) {
      final file = File('assets/locales/$lang.json');
      expect(file.existsSync(), isTrue, reason: 'missing ${file.path}');

      final map =
          (jsonDecode(file.readAsStringSync()) as Map).cast<String, dynamic>();

      map.forEach((key, value) {
        if (_allowedKeys.contains(key) || value is! String) return;
        final haystack = value.toLowerCase();
        for (final needle in _steering) {
          if (haystack.contains(needle.toLowerCase())) {
            offenders.add('$lang → $key: "$value"');
            break;
          }
        }
      });
    }

    expect(
      offenders,
      isEmpty,
      reason: 'Guideline 3.1.1: these strings steer users to the web app.\n'
          'Fix them in tool/flutter_extra_keys.json (the SOURCE) and rerun\n'
          '`node tool/sync_locales.js` — editing assets/locales/ directly is\n'
          'reverted on the next regeneration.\n\n${offenders.join('\n')}',
    );
  });

  test('all locales carry the same keys', () {
    // Divergent key sets mean some language silently falls back to English.
    final sets = <String, Set<String>>{};
    for (final lang in _langs) {
      final map = (jsonDecode(File('assets/locales/$lang.json').readAsStringSync())
              as Map)
          .cast<String, dynamic>();
      sets[lang] = map.keys.toSet();
    }
    final reference = sets['en']!;
    for (final entry in sets.entries) {
      expect(
        entry.value.difference(reference),
        isEmpty,
        reason: '${entry.key} has keys en does not',
      );
      expect(
        reference.difference(entry.value),
        isEmpty,
        reason: '${entry.key} is missing keys that en has',
      );
    }
  });
}
